// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearHogwartsSorting.png
var resourceKrankyBearHogwartsSortingPngData []byte
var resourceKrankyBearHogwartsSortingPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHogwartsSorting.png",
	StaticContent: resourceKrankyBearHogwartsSortingPngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}

//go:embed assets/images/KrankyBearChristmasGrinch.png
var resourceKrankyBearChristmasGrinchPngData []byte
var resourceKrankyBearChristmasGrinchPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearChristmasGrinch.png",
	StaticContent: resourceKrankyBearChristmasGrinchPngData,
}

//go:embed assets/images/KrankyBearChristmas.png
var resourceKrankyBearChristmasPngData []byte
var resourceKrankyBearChristmasPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearChristmas.png",
	StaticContent: resourceKrankyBearChristmasPngData,
}

//go:embed assets/images/KrankyBearVikingHelmet.png
var resourceKrankyBearVikingHelmetPngData []byte
var resourceKrankyBearVikingHelmetPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearVikingHelmet.png",
	StaticContent: resourceKrankyBearVikingHelmetPngData,
}

//go:embed assets/images/KrankyBearBeret.png
var resourceKrankyBearBeretPngData []byte
var resourceKrankyBearBeretPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearBeret.png",
	StaticContent: resourceKrankyBearBeretPngData,
}

//go:embed assets/images/KrankyBearBeanieMultiColor.png
var resourceKrankyBearBeanieMultiColorPngData []byte
var resourceKrankyBearBeanieMultiColorPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearBeanieMultiColor.png",
	StaticContent: resourceKrankyBearBeanieMultiColorPngData,
}

//go:embed assets/images/KrankyBearCowboyBrown.png
var resourceKrankyBearCowboyBrownPngData []byte
var resourceKrankyBearCowboyBrownPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearCowboyBrown.png",
	StaticContent: resourceKrankyBearCowboyBrownPngData,
}

//go:embed assets/images/KrankyBearFedoraRed.png
var resourceKrankyBearFedoraRedPngData []byte
var resourceKrankyBearFedoraRedPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearFedoraRed.png",
	StaticContent: resourceKrankyBearFedoraRedPngData,
}

//go:embed assets/images/KrankyBear.png
var resourceKrankyBearPngData []byte
var resourceKrankyBearPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBear.png",
	StaticContent: resourceKrankyBearPngData,
}

//go:embed assets/images/KrankyBearTrapperRedPlaid.png
var resourceKrankyBearTrapperRedPlaidPngData []byte
var resourceKrankyBearTrapperRedPlaidPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearTrapperRedPlaid.png",
	StaticContent: resourceKrankyBearTrapperRedPlaidPngData,
}

//go:embed assets/images/http418.png
var resourceHttp418PngData []byte
var resourceHttp418Png = &fyne.StaticResource{
	StaticName:    "assets/images/http418.png",
	StaticContent: resourceHttp418PngData,
}

//go:embed assets/sounds/boing.mp3
var resourceBoingMp3Data []byte
var resourceBoingMp3 = &fyne.StaticResource{
	StaticName:    "assets/sounds/boing.mp3",
	StaticContent: resourceBoingMp3Data,
}

// "Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning." Winston Churchill, November 10, 1942
