[Details]
ID = "com.github.amarillier.KrankyBearTailer"
Name = "KrankyBear Tailer"
Creator = "Allan Marillier"
  Version = "0.2.0"
Build = 1
Icon = "KrankyBearHogwartsSorting.png"

[Migrations]
  fyneDo = true

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"